
function OtrixDomNode(e){this.elm=e;}
OtrixDomNode.prototype.addEventListener=function(anEvent,aListener,useCapture){otrix.addEventListener(this.elm,anEvent,aListener,useCapture);};OtrixDomNode.prototype.canSetInnerHTML=function(){var result=true;if(otrix.isIE){var nodeName=this.elm.nodeName;if(nodeName=="COL"){result=false;}
else if(nodeName=="COLGROUP"){result=false;}
else if(nodeName=="FRAMESET"){result=false;}
else if(nodeName=="HTML"){result=false;}
else if(nodeName=="STYLE"){result=false;}
else if(nodeName=="TABLE"){result=false;}
else if(nodeName=="TBODY"){result=false;}
else if(nodeName=="TFOOT"){result=false;}
else if(nodeName=="THEAD"){result=false;}
else if(nodeName=="TITLE"){result=false;}
else if(nodeName=="TR"){result=false;}}
return result;};OtrixDomNode.prototype.getAttribute=function(attrn){return otrix.getAttribute(this.elm,attrn);};OtrixDomNode.prototype.getFirstChild=function(){var r=null;var childNodes=this.elm.childNodes;for(var i=0;i<childNodes.length;i++){if(childNodes[i].tagName){r=childNodes[i];break;}}
return otrix.getUIElementById(r);};OtrixDomNode.prototype.getForm=function(){return otrix.findAncestor(this.elm,null,null,"FORM");};OtrixDomNode.prototype.getHeight=function(){return parseInt(this.elm.offsetHeight);};OtrixDomNode.prototype.getLastChild=function(){var r=null;var childNodes=this.elm.childNodes;for(var i=childNodes.length-1;i>=0;i--){if(childNodes[i].tagName){r=childNodes[i];break;}}
return otrix.getUIElementById(r);};OtrixDomNode.prototype.getLeft=function(){return parseInt(this.elm.style.left);};OtrixDomNode.prototype.getPageLeft=function(){if(this.elm.pageX){return this.elm.pageX;}
var nLeftPos=0;var eParElement=this.elm;while(!otrix.isNull(eParElement)){if(otrix.isIE){if((eParElement.tagName!="TABLE")&&(eParElement.tagName!="BODY")){nLeftPos+=eParElement.clientLeft;}}
else{if(eParElement.tagName=="TABLE"){var nParBorder=parseInt(eParElement.border);if(isNaN(nParBorder)){var nParFrame=eParElement.getAttribute('frame');if(!otrix.isNull(nParFrame)){nLeftPos+=1;}}
else if(nParBorder>0){nLeftPos+=nParBorder;}}}
nLeftPos+=eParElement.offsetLeft;eParElement=eParElement.offsetParent;}
return nLeftPos;};OtrixDomNode.prototype.getPageTop=function(){if(this.elm.pageY){return this.elm.pageY;}
var nTopPos=0;var eParElement=this.elm;while(!otrix.isNull(eParElement)){if(otrix.isIE){if((eParElement.tagName!="TABLE")&&(eParElement.tagName!="BODY")){nTopPos+=eParElement.clientTop;}}
else{if(eParElement.tagName=="TABLE"){var nParBorder=parseInt(eParElement.border);if(isNaN(nParBorder)){var nParFrame=eParElement.getAttribute('frame');if(!otrix.isNull(nParFrame)){nTopPos+=1;}}
else if(nParBorder>0){nTopPos+=nParBorder;}}}
nTopPos+=eParElement.offsetTop;eParElement=eParElement.offsetParent;}
return nTopPos;};OtrixDomNode.prototype.getTop=function(){return parseInt(this.elm.style.top);};OtrixDomNode.prototype.getType=function(){return otrix.getType(this);};OtrixDomNode.prototype.getWidth=function(){return parseInt(this.elm.offsetWidth);};OtrixDomNode.prototype.hide=function(rs){if(this.elm.style.visibility!="hidden"){this.elm.style.visibility="hidden";}
if(rs===true){if(this.elm.style.display!="none"){this.elm.style.display="none";}}};OtrixDomNode.prototype.isEnabled=function(){return(this.getAttribute(otrix.PROP_DISABLED)!="true");};OtrixDomNode.prototype.isVisible=function(){return!(this.elm.style.visibility=="hidden"||this.elm.style.display=="none");};OtrixDomNode.prototype.moveTo=function(x,y){otrix.debug("before x:"+x+"; y:"+y);this.elm.style.left=x+"px";this.elm.style.top=y+"px";otrix.debug("x:"+this.elm.style.left+"; y:"+this.elm.style.top);};OtrixDomNode.prototype.setHeight=function(v){this.elm.offsetHeight=v+"px";};OtrixDomNode.prototype.setLeft=function(v){this.elm.style.left=v+"px";};OtrixDomNode.prototype.setTop=function(v){this.elm.style.top=v+"px";};OtrixDomNode.prototype.setType=function(type){otrix.setAttribute(this.elm,otrix.PROP_TYPE,type);};OtrixDomNode.prototype.setWidth=function(v){this.elm.offsetWidth=v+"px";};OtrixDomNode.prototype.show=function(x,y,x2,y2){if(otrix.isNumber(x)||otrix.isNumber(y)){var w=this.getWidth();var sl=otrix.getScrollLeft();var cw=otrix.getClientWidth();var h=this.getHeight();var ch=otrix.getClientHeight();var st=otrix.getScrollTop();if(otrix.isNumber(x)){if(x>cw+sl-w){if(otrix.isNumber(x2)){x=x2;}else{x=x-w;}}
if(x<0){x=0;}}
if(otrix.isNumber(y)){if(y+h>ch+st){y=ch+st-h;}
if(y<0){y=0;}}
this.moveTo(x,y);}
if(this.elm.style.visibility!="visible"){this.elm.style.visibility="visible";}
if(this.elm.style.display!==""){this.elm.style.display="";}};function OtrixUIElement(e){this.OtrixDomNode(e);}
OtrixUIElement.prototype.applyClass=function(){var css=this.getClass();if(otrix.isString(css)){if(this.elm.className!=css){this.elm.className=css;}}};OtrixUIElement.prototype.collapse=function(){var cc=this.getChildContainer();if(!otrix.isNull(cc)){cc.hide();var pc=this.getComponent();if(!otrix.isNull(pc)){var sn=pc.getSelectedElement();if(this.isAncestor(sn)){this.select();}}}};OtrixUIElement.prototype.disable=function(){this.setUIAttribute(otrix.PROP_DISABLED,true);};OtrixUIElement.prototype.enable=function(){this.setUIAttribute(otrix.PROP_DISABLED,false);};OtrixUIElement.prototype.expand=function(){var cc=this.getChildContainer();if(!otrix.isNull(cc)){cc.show();}};OtrixUIElement.prototype.fireCSEvent=function(eventName){var jsFunc=otrix.executeMethod(this,"getOn"+eventName,null);return otrix.executeMethod(null,jsFunc,this);};OtrixUIElement.prototype.fireSSEvent=function(eventName,target,partialRefresh,callback,params){otrix.fireEvent(this.getForm(),this.elm.id,eventName,target,partialRefresh,callback,params);};OtrixUIElement.prototype.focus=function(){if(!this.isFocussed()){otrix.setFocussedElement(this);}};OtrixUIElement.prototype.fireEvent=function(eventName,target,partialRefreshFor,callback,params){var fireServerSide=this.fireCSEvent(eventName);if(fireServerSide){this.fireSSEvent(eventName,target,partialRefreshFor,callback,params);}};OtrixUIElement.prototype.getAttribute=function(attrn,p,s){var tmp=otrix.getAttribute(this.elm,attrn);if(p===true&&!otrix.NaES(tmp)){var pc=this.getComponent();if(!otrix.isNull(pc)){if(!otrix.isNull(s)){tmp=otrix.getAttribute(pc.elm,attrn+s);}
else{tmp=otrix.getAttribute(pc.elm,attrn+this.getType());}}}
return tmp;};OtrixUIElement.prototype.getChildContainer=function(){return otrix.getUIElementById(this.elm.id+"_cc");};OtrixUIElement.prototype.getComponent=function(){var c=this.elm[otrix.PROP_PARENT_COMPONENT];if(otrix.isNull(c)){c=otrix.findAncestor(this.elm,otrix.PROP_COMPONENT);if(!otrix.isNull(c)){this.elm[otrix.PROP_PARENT_COMPONENT]=c.id;}}
return otrix.getUIElementById(c);};OtrixUIElement.prototype.getClass=function(){var css=null;if(!this.isEnabled()){css=this.getDisabledClass();}
else{if(this.isSelected()){css=this.getSelectedClass();}
if(this.isHovered()||this.isFocussed()){if(!otrix.isNull(css)){css=css+" "+this.getHoverClass();}
else{css=this.getHoverClass();}}
if(!css){css=this.getDefaultClass();}}
if(!css){css="";}
return css;};OtrixUIElement.prototype.getDefaultClass=function(){return this.getAttribute(otrix.PROP_DEFAULT_CLASS,true);};OtrixUIElement.prototype.getDisabledClass=function(){return this.getAttribute(otrix.PROP_DISABLED_CLASS,true);};OtrixUIElement.prototype.getFireEvent=function(){return this.getAttribute(otrix.PROP_FIRE_EVENT)!="false";};OtrixUIElement.prototype.getFirstChild=function(oe){var cc=this.getChildContainer();if(!otrix.isNull(cc)){cc=otrix.findDescendant(cc.elm,otrix.PROP_TYPE);cc=otrix.getUIElementById(cc);if(oe===true&&!otrix.isNull(cc)&&!cc.isEnabled()){cc=cc.getNextSibling(true);}}
return cc;};OtrixUIElement.prototype.getFirstSibling=function(oe){var r=null;var t=this.getType();var tmp=this.elm.parentNode.firstChild;while(!otrix.isNull(tmp)){if(otrix.getType(tmp)==t){r=tmp;break;}
tmp=tmp.nextSibling;}
r=otrix.getUIElementById(r);if(oe===true&&!otrix.isNull(r)&&!r.isEnabled()){r=r.getNextSibling(true);}
return r;};OtrixUIElement.prototype.getHoverClass=function(){return this.getAttribute(otrix.PROP_HOVER_CLASS,true);};OtrixUIElement.prototype.getLastChild=function(){var r=this.getFirstChild();if(r){r=r.getLastSibling();}
return r;};OtrixUIElement.prototype.getLastSibling=function(oe){var r=null;var t=this.getType();var tmp=this.elm.parentNode.lastChild;while(!otrix.isNull(tmp)){if(otrix.getType(tmp)==t){r=tmp;break;}
tmp=tmp.previousSibling;}
r=otrix.getUIElementById(r);if(oe===true&&!otrix.isNull(r)&&!r.isEnabled()){r=r.getPreviousSibling(true);}
return r;};OtrixUIElement.prototype.getNextSibling=function(oe){var r=null;var t=this.getType();var tmp=this.elm.nextSibling;while(!otrix.isNull(tmp)){if(otrix.getType(tmp)==t){r=tmp;break;}
tmp=tmp.nextSibling;}
r=otrix.getUIElementById(r);if(oe===true&&!otrix.isNull(r)&&!r.isEnabled()){r=r.getNextSibling(true);}
return r;};OtrixUIElement.prototype.getParent=function(){var c=this.elm[otrix.PROP_PARENT];if(!c){var pc=otrix.findAncestor(this.elm.parentNode,"id");if(otrix.isNull(pc)){return null;}
var idx=pc.id.lastIndexOf("_cc");c=pc.id.substring(0,idx);if(otrix.NaES(c)){this.elm[otrix.PROP_PARENT]=c;}}
return otrix.getUIElementById(c);};OtrixUIElement.prototype.getPreviousSibling=function(oe){var r=null;var t=this.getType();var tmp=this.elm.previousSibling;while(!otrix.isNull(tmp)){if(otrix.getType(tmp)==t){r=tmp;break;}
tmp=tmp.previousSibling;}
r=otrix.getUIElementById(r);if(oe===true&&!otrix.isNull(r)&&!r.isEnabled()){r=r.getPreviousSibling(true);}
return r;};OtrixUIElement.prototype.hasChild=function(){return(!otrix.isNull(this.getChildContainer()));};OtrixUIElement.prototype.getSelectedClass=function(){return this.getAttribute(otrix.PROP_SELECTED_CLASS,true);};OtrixUIElement.prototype.hover=function(){if(!this.isHovered()){otrix.setHoveredElement(this);}};OtrixUIElement.prototype.isAncestor=function(n){var tmp=n;var res=false;while(!otrix.isNull(tmp)){if(tmp.elm==this.elm){res=true;break;}
tmp=tmp.getParent();}
return res;};OtrixUIElement.prototype.isExpanded=function(){var cc=this.getChildContainer();return(!otrix.isNull(cc))?(cc.elm.style.visibility!="hidden"&&cc.elm.style.display!="none"):false;};OtrixUIElement.prototype.isFocussed=function(){return this.elm.focussed||otrix.areNodeEqual(this,otrix.getFocussedElement());};OtrixUIElement.prototype.isHovered=function(){return this.elm.hovered||otrix.areNodeEqual(this,otrix.getHoveredElement());};OtrixUIElement.prototype.isSelected=function(){return(this.getAttribute(otrix.PROP_SELECTED)=="true");};OtrixUIElement.prototype.onBlur=function(){otrix.setFocussedElement(null);};OtrixUIElement.prototype.onClick=function(){this.select();};OtrixUIElement.prototype.onDoubleClick=function(){};OtrixUIElement.prototype.onFocus=function(){this.focus();};OtrixUIElement.prototype.onKeyPress=function(evt){var c=this.getComponent();if(!otrix.isNull(c)){c.onKeyPress(evt);}};OtrixUIElement.prototype.onMouseOut=function(){otrix.setHoveredElement(null);};OtrixUIElement.prototype.onMouseOver=function(){this.hover();};OtrixUIElement.prototype.queueEvent=function(evtSrc,evtName,evtValue){if(otrix.NaES(evtSrc)){var pcmp=this.getComponent();if(!otrix.isNull(pcmp)){pcmp.queueEvent(evtSrc,evtName,evtValue);}}};OtrixUIElement.prototype.removeChildren=function(){var cc=this.getChildrenContainer();if(!otrix.isNull(cc)){var pn=cc.parentNode;if(!otrix.isNull(pn)){pn.removeChild(cc);}}};OtrixUIElement.prototype.repaint=function(){this.applyClass();};OtrixUIElement.prototype.replaceChildren=function(newChildren){this.removeChildren();this.appendChildren();};OtrixUIElement.prototype.select=function(){var pc=this.getComponent();if(!otrix.isNull(pc)){pc.selectElement(this);}};OtrixUIElement.prototype.setUIAttribute=function(n,v){if(otrix.setAttribute(this.elm,n,v)){this.repaint();}};OtrixUIElement.prototype.toggle=function(){if(this.isExpanded()){this.collapse();}
else{this.expand();}};OtrixUIElement.prototype.unselect=function(){if(this.isSelected()){var pc=this.getComponent();if(!otrix.isNull(pc)){pc.unselectElement(this);}}};OtrixUIElement._extends(OtrixDomNode);function OtrixRPCContext(e){this.OtrixDomNode(e);}
OtrixRPCContext.prototype.getDocument=function(){var doc=null;if(this.elm.contentDocument){doc=this.elm.contentDocument;}
else{if(this.elm.contentWindow){doc=this.elm.contentWindow.document;}
else{if(this.elm.document){doc=this.elm.document;}}}
return doc;};OtrixRPCContext.prototype.importElementById=function(id,doc){return otrix.importNode(this.getElementById(id),doc);};OtrixRPCContext.prototype.getElementById=function(id){return this.getDocument().getElementById(id);};OtrixRPCContext.prototype.getResultAsHtml=function(){return this.getElementById("orfs");};OtrixRPCContext.prototype.getTarget=function(){return this.elm.oTarget;};OtrixRPCContext.prototype.isAvailable=function(){return this.elm.oAvailable;};OtrixRPCContext.prototype.release=function(){this.elm.oCallback=null;this.elm.oSource=null;this.elm.oAvailable=true;};OtrixRPCContext.prototype.acquire=function(){this.elm.oAvailable=false;};OtrixRPCContext.prototype.getCallback=function(){return this.elm.oCallback;};OtrixRPCContext.prototype.setCallback=function(value){this.elm.oCallback=value;};OtrixRPCContext.prototype.setTarget=function(value){this.elm.oTarget=value;};OtrixRPCContext.prototype.submit=function(srcFrm,partialRefreshFor,partialRefreshCallback,params){var qs=otrix.formToQueryString(srcFrm);if(otrix.NaES(partialRefreshFor)){this.setTarget(partialRefreshFor);qs=qs+"&com.otrix.faces.prfcid="+partialRefreshFor;}
qs=qs+"&com.otrix.faces.RPC_CONTEXT_ID="+this.elm.id;if(otrix.NaES(params)){var arrayParams=params.split(";");for(var nbParams=0;nbParams<arrayParams.length;nbParams++){var param=arrayParams[nbParams];if(otrix.NaES(param)){var paramNameValue=param.split("=");if(paramNameValue.length==2){qs=qs+"&"+paramNameValue[0]+"="+paramNameValue[1];}}}}
this.setCallback(partialRefreshCallback);this.getDocument().location.replace(qs);};OtrixRPCContext._extends(OtrixDomNode);otrix.getUIElementById=function(id){return otrix.factory.getInstance(id);};otrix.getTargetUIElement=function(e,t){var a=otrix.findAncestor(e,otrix.PROP_TYPE,t);return otrix.getUIElementById(a);};function OtrixUIComponent(e){this.OtrixUIElement(e);}
OtrixUIComponent.prototype.allowMultiSelect=function(){return(this.getAttribute(otrix.PROP_ALLOW_MULTI_SELECT)=="true");};OtrixUIComponent.prototype.clearSelection=function(){if(!otrix.isNull(this.elm.SELECTED_ELEMENTS)){for(var i=this.elm.SELECTED_ELEMENTS.length-1;i>=0;i--){var pe=otrix.getUIElementById(this.elm.SELECTED_ELEMENTS[i]);if(!otrix.isNull(pe)){pe.unselect();}}}};OtrixUIComponent.prototype.getComponent=function(){return null;};OtrixUIComponent.prototype.getSelectedElement=function(){return this.elm.selectedElement;};OtrixUIComponent.prototype.onKeyPress=function(evt){};OtrixUIComponent.prototype.onFocus=function(){};OtrixUIComponent.prototype.onMouseOver=function(){};OtrixUIComponent.prototype.queueEvent=function(evtSrc,evtName,evtValue){var eq=new OtrixEventQueue(this.elm.id);if(!otrix.isNull(eq)){eq.queueEvent(evtSrc,evtName,evtValue);}};OtrixUIComponent.prototype.selectElement=function(oe){if(!otrix.isNull(oe)&&!oe.isSelected()){if(!this.allowMultiSelect()){this.clearSelection();}
if(otrix.isNull(this.elm.SELECTED_ELEMENTS)){this.elm.SELECTED_ELEMENTS=[];}
this.elm.SELECTED_ELEMENTS[this.elm.SELECTED_ELEMENTS.length]=oe.elm;oe.setUIAttribute(otrix.PROP_SELECTED,true);oe.queueEvent(oe.elm.id,"select","true");}};OtrixUIComponent.prototype.unselectElement=function(oe){if(!otrix.isNull(oe)&&oe.isSelected()){oe.setUIAttribute(otrix.PROP_SELECTED,false);if(!otrix.isNull(this.elm.SELECTED_ELEMENTS)){for(var i=0;i<this.elm.SELECTED_ELEMENTS.length;i++){if(this.elm.SELECTED_ELEMENTS[i]==oe.elm){this.elm.SELECTED_ELEMENTS[i]=null;break;}}}}};OtrixUIComponent._extends(OtrixUIElement);function OtrixCommand(e){this.OtrixUIElement(e);}
OtrixCommand.prototype.click=function(){if((!this.isEnabled())){return;}
var href=this.getHref();if(otrix.NaES(href)){var t=this.findTarget();t.location.href=href;}
else{this.fireEvent(otrix.event.EVENT_CLICK,this.getTarget());}};OtrixCommand.prototype.findTarget=function(){var t=parent.frames[this.getTarget()];if(otrix.isNull(t)){t=window;}
return t;};OtrixCommand.prototype.getHref=function(){return this.getAttribute(otrix.PROP_HREF);};OtrixCommand.prototype.getTarget=function(){return this.getAttribute(otrix.PROP_TARGET);};OtrixCommand.prototype.onClick=function(){this.click();};OtrixCommand._extends(OtrixUIElement);function OtrixPagerCommand(e){this.OtrixCommand(e);}
OtrixPagerCommand.prototype.click=function(){if((!this.isEnabled())){return;}
var pagerId=this.getPagerId();if(otrix.NaES(pagerId)){var forComponentId=this.getComponentId();this.fireEvent("gotoPage",null,pagerId,otrix.onPaging,"pagerForComponent="+forComponentId);}};OtrixPagerCommand.prototype.getPager=function(){var tmpNode=this.elm.parentNode;var result=null;while(!otrix.isNull(tmpNode)){result=tmpNode.id;if(otrix.NaES(result)){break;}
tmpNode=tmpNode.parentNode;}
return otrix.getUIElementById(result);};OtrixPagerCommand.prototype.getComponentId=function(){var result=null;var pager=this.getPager();if(!otrix.isNull(pager)){result=pager.getAttribute("ofcid");}
return result;};OtrixPagerCommand.prototype.getPagerId=function(){var result=null;var pager=this.getPager();if(!otrix.isNull(pager)){result=pager.elm.id;}
return result;};OtrixPagerCommand._extends(OtrixCommand);otrix.onBlur=function(evt){var xEvt=otrix.toEvent(evt);if(otrix.isNull(xEvt)){return;}
var t=otrix.getTargetUIElement(xEvt.target);if(!otrix.isNull(t)&&t.isEnabled()){t.onBlur(xEvt);}};otrix.onClick=function(evt){var xEvt=otrix.toEvent(evt);if(otrix.isNull(xEvt)){return;}
var t=otrix.getTargetUIElement(xEvt.target);if(!otrix.isNull(t)&&t.isEnabled()){t.onClick(xEvt);}};otrix.onDoubleClick=function(evt){var xEvt=otrix.toEvent(evt);if(otrix.isNull(xEvt)){return;}
var t=otrix.getTargetUIElement(xEvt.target);if(!otrix.isNull(t)&&t.isEnabled()){t.onDoubleClick(xEvt);}};otrix.onKeyDown=function(evt){var xEvt=otrix.toEvent(evt);if(otrix.isNull(xEvt)){return;}
var c=otrix.getFocussedElement();if(!otrix.isNull(c)&&c.isEnabled()){c.onKeyPress(xEvt);}};otrix.onMouseOver=function(evt){var xEvt=otrix.toEvent(evt);if(otrix.isNull(xEvt)){return;}
var t=otrix.getTargetUIElement(xEvt.target);if(!otrix.isNull(t)){if(t.isEnabled()){t.onMouseOver(xEvt);}}
else{var p=otrix.getHoveredElement();if(!otrix.isNull(p)){p.onMouseOut(xEvt);}}};otrix.onFocus=function(evt){var xEvt=otrix.toEvent(evt);if(otrix.isNull(xEvt)){return;}
var t=otrix.getTargetUIElement(xEvt.target);if(!otrix.isNull(t)&&t.isEnabled()){t.onFocus(xEvt);}};otrix.getFocussedElement=function(){return otrix.focussedElement;};otrix.setFocussedElement=function(e){var pe=otrix.getFocussedElement();otrix.focussedElement=e;if(!otrix.isNull(pe)){pe.repaint();}
if(!otrix.isNull(e)){e.repaint();}};otrix.getHoveredElement=function(){return otrix.hoveredElement;};otrix.setHoveredElement=function(e){var pe=otrix.getHoveredElement();otrix.hoveredElement=e;if(!otrix.isNull(pe)){pe.repaint();}
if(!otrix.isNull(e)){e.repaint();}};